<?php

namespace CLBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findBySearch($searchstr)
    {
        $dql = 'SELECT c 
                FROM CLBundle:Contact c 
                WHERE c.name LIKE :searchstr OR c.surname LIKE :searchstr 
                ORDER BY c.surname ASC';
        return $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('searchstr', '%'.$searchstr.'%')
            ->getResult();
    }
}
